# Generated by Django 3.0.2 on 2020-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
